### ISSUE TITLE
how to show the structure directly on the web without dash?

### ISSUE THREAD

**Issue by haidi-ustc** [materialsproject/crystaltoolkit#238]
Hi,@mkhorton 
Recently, I want to display the structure on my own website. Now  I use the  crystal-toolkit via iframe in html.  This works fine, but  it takes a long time to load the components. I found that  it requires  to load a 7.3MB js file while open a web page for the first time, namely, dash-mp-components.min.js.  Is there any better way to load the structure faster? Thanks.

**Comment by mkhorton** [comment]
Hi @haidi-ustc, thanks for asking about this. Tagging @codytodonnell who may have insight, do you know why the bundle is so large right now?

The three.js library this uses is ~ 1 MB, so there will necessarily be a large-ish first load. In deployment, we also use `unpkg` as a CDN to speed up retrieval, but I agree 7 MB seems unexpected.

It's possible I'm getting confused between the .min.js size and the gzipped size too, because I believe we deploy these assets compressed too (this is handled by the web server, so the actual transfer size is that much smaller--.js compresses quite well).

**Comment by mkhorton** [comment]
@haidi-ustc if you're willing to share a link to your website, I would also be happy to take a look (as a courtesy) to verify that the slowdown is due to the bundle load size, and may be able to make a recommendation for alternatives depending on the use case

**Comment by haidi-ustc** [comment]
> @haidi-ustc if you're willing to share a link to your website, I would also be happy to take a look (as a courtesy) to verify that the slowdown is due to the bundle load size, and may be able to make a recommendation for alternatives depending on the use case

Thank you very much, now we have solved the problem according to your suggestion.   Since we use a localhost, I sorry that I cannot share the website now. Thanks again.
