### ISSUE TITLE
Most examples apps broken

### ISSUE THREAD

**Issue by janosh** [materialsproject/crystaltoolkit#361]
Total example apps:

```sh
ls crystal_toolkit/apps/examples/*.py | wc -l
>>> 23  # -2 for utils and __init__
```

Found **6 broken** out of **8 tested**

1. ✅ `apps/examples/pourbaix.py`
1. ✅ `apps/examples/structure.py`
1. 💀 `apps/examples/phase_diagram.py`
1. 💀 `apps/examples/relaxation_trajectory.py`
1. 💀 `apps/examples/structure_magnetic.py`
1. 💀 `apps/examples/transformations_minimal.py`
1. 💀 `apps/examples/transformations.py`
1. 💀 `apps/examples/write_structure_screenshot_to_file.py`

Below are app screenshots.

## ✅ `apps/examples/pourbaix.py`

![pourbaix](https://github.com/materialsproject/crystaltoolkit/assets/30958850/30971b87-26db-4112-8926-2620d89de62c)

## ✅ `apps/examples/structure.py`

![structure](https://github.com/materialsproject/crystaltoolkit/assets/30958850/2778ce1a-44b0-46e1-80e0-9f044108064e)

## 💀 `apps/examples/phase_diagram.py`

![phase_diagram](https://github.com/materialsproject/crystaltoolkit/assets/30958850/cb8d233b-0c13-465c-995d-4598751cb348)

## 💀 `apps/examples/relaxation_trajectory.py`

![relaxation_trajectory](https://github.com/materialsproject/crystaltoolkit/assets/30958850/4fb371b8-b42b-41cc-b016-a7d549658dba)

## 💀 `apps/examples/structure_magnetic.py`

![structure_magnetic](https://github.com/materialsproject/crystaltoolkit/assets/30958850/150ffb57-f5cf-4305-bacf-48403596e8d9)

## 💀 `apps/examples/transformations_minimal.py`

![transformations_minimal](https://github.com/materialsproject/crystaltoolkit/assets/30958850/adc3b831-5e0a-44d5-a75c-e41f3b29a427)

## 💀 `apps/examples/transformations.py`

![transformations](https://github.com/materialsproject/crystaltoolkit/assets/30958850/615133b0-1aa2-4cf4-ad48-fd3945a0d198)

## 💀 `apps/examples/write_structure_screenshot_to_file.py`

![write_structure_screenshot_to_file](https://github.com/materialsproject/crystaltoolkit/assets/30958850/6b2f3af8-ff64-4774-b686-ad1a66afdb4b)

**Comment by mkhorton** [comment]
Thanks for this summary. I think next step here is to make sure these are working, and add to automated testing (e.g., making sure they run without console errors).

Quick impressions:

- ` apps/examples/phase_diagram.py` probably affected by #264, because a lot of PD improvements were implemented initially in `web` and have not been upstreamed. It could benefit a lot from the kind of work that was done for the Pourbaix app, which is a lot cleaner comparatively speaking (which is why I expect the Pourbaix demo still works too)
- `apps/examples/structure_magnetic.py` looks like a trivial MPRester / document model change
- `apps/examples/write_structure_screenshot_to_file.py` this isn't really a real "app" but is a workaround for not being able to generate crystal images via script, since the rendering is done in-browser and requires a WebGL context, nevertheless not sure what the error is here -- the MP team will eventually have to tackle this issue to generate images as new materials are added to the MP website

**Comment by tsmathis** [comment]
Re: the screenshot generation script: There previously was an `imageRequest` property within the `CrystalToolkitScene` component in `mp-react-components`. At some point in the last two years that property and the associated hooks were removed from `mp-react-components`, I haven't found the exact commit this occurred at yet so I'm not sure what the reason was for removing it.

I had to re-introduce the `imageRequest` prop for a recent ad hoc image generation script for new structures.

**Comment by mkhorton** [comment]
Sorry @tsmathis, sounds frustrating!

I can offer some background on those props for context. Basically, there are two ways of handling a screenshot or 3D model export. Both of these ways can, in principle, be used together:

1. Trigger the download completely client-side
    * Pros: fast
    * Cons: server cannot retrieve downloaded data
2. Encode the image/file as a prop, b64-encoded
    * Pros: server can then modify this image (for example, we might want to add a legend, or generate screenshots automatically and upload these to a database)
    * Cons: I felt uneasy about putting a relatively "large" string into a prop

I don't remember exactly, but I think potentially 1. was removed in favor of 2.? I think the capability was always there somehow, it was just a question of whether it was done client-side or server-side.

Regardless of outcome, the ultimate aim was to add both some legend tiles + a credit string to the image via `Pillow`, as a polite nudge to people to remember to credit the source of the image when it's re-used. This was on the backlog.
