### ISSUE TITLE
redis.exceptions.ConnectionError

### ISSUE THREAD

**Issue by dwinston** [materialsproject/crystaltoolkit#68]
I don't see any instructions for avoiding a Redis connection error or for installing Redis, e.g. in the Dockerfile. Here's what I do:

```
docker run -p 127.0.0.1:6379:6379 -d redis
```

It is important to not just `-p 6379:6379` on some networks, because that exposes an insecure Redis instance. For example, I got my MAC address banned on the LBL network for exposing it.

Can we add instructions somewhere?

**Comment by peterschindler** [comment]
When I try to run the view function (in a Jupyter notebook on a Google colab server with pymatgen, dash and crystal_toolkit installed) I am also getting a connection error. Not sure, if that is the same error as what Donny described.
Btw, thanks again for the great workshop this year!

---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/urllib3/connection.py in _new_conn(self)
    158             conn = connection.create_connection(
--> 159                 (self._dns_host, self.port), self.timeout, **extra_kw)

**Comment by mkhorton** [comment]
Hi @peterschindler, thanks for trying this out! Crystal Toolkit still in "pre-release" currently, and specifically the function you are trying to call is not the one that was demoed in the workshop. If you want the workshop version, you can install from the workshop fork:

https://github.com/jmmshn/crystaltoolkit@mp_workshop2019#egg=crystal-toolkit

We wanted to be able to have interactive crystal/molecule viewing in the workshop which is why we installed it because we thought it might help with the teaching, but the code is not ready for public use just yet, though it will be soon. We probably should have made that clearer.

I'll leave this thread open so I can update it when we have the next official release, which should be before the end of the month. Documentation + a paper will then soon be to follow :-)

**Comment by peterschindler** [comment]
Got it - thank you @mkhorton !
I found the visualization during the workshop super useful and don't know of any other package that can do that within Jupyter! :)

**Comment by mkhorton** [comment]
Closing this issue because it's now stale, thank you both for trying this out back then!
